export const SEND_LOCATION_REQUEST = "SEND_LOCATION_REQUEST";
export const SEND_LOCATION_SUCCESS = "SEND_LOCATION_SUCCESS";
export const SEND_LOCATION_FAIL = "SEND_LOCATION_FAIL";

export const FETCH_USER_LOCATION_REQUEST = "FETCH_USER_LOCATION_REQUEST";
export const FETCH_USER_LOCATION_SUCCESS = "FETCH_USER_LOCATION_SUCCESS";
export const FETCH_USER_LOCATION_FAIL = "FETCH_USER_LOCATION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
